name: Tests

on: [pull_request]

jobs:
  check:
    name: Test source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.0'
      - name: Install NPM dependencies
        run: npm i
      - name: Lint
        run: npm run lint
      - name: TypeScript check
        run: npm run tsc
      - name: Build packages
        run: npm run build-packages
      - name: Unit tests
        run: npm run test
